# Generated by Django 5.2.1 on 2025-05-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferencePose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pose_type', models.CharField(choices=[('yoga', '요가'), ('crossfit', '크로스핏')], max_length=20)),
                ('csv_path', models.CharField(max_length=255)),
                ('row_index', models.IntegerField(default=0)),
            ],
        ),
    ]
