# Generated by Django 5.2.1 on 2025-06-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pose_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencepose",
            name="pose_type",
            field=models.CharField(
                choices=[("squat", "스쿼트"), ("cat", "고양이")], max_length=20
            ),
        ),
    ]
