# Generated by Django 5.2.1 on 2025-06-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pose_app", "0002_alter_referencepose_pose_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="referencepose",
            name="category",
            field=models.CharField(
                choices=[("크로스핏", "크로스핏"), ("요가", "요가")],
                default="크로스핏",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="referencepose",
            name="csv_path",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="referencepose",
            name="pose_type",
            field=models.CharField(
                choices=[
                    ("squat", "스쿼트"),
                    ("cat", "고양이"),
                    ("cobra", "코브라"),
                    ("warrior2", "전사2"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="referencepose",
            name="row_index",
            field=models.IntegerField(),
        ),
    ]
