# Generated by Django 5.2.1 on 2025-07-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pose_app', '0003_referencepose_category_alter_referencepose_csv_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencepose',
            name='pose_type',
            field=models.CharField(choices=[('squat', '스쿼트'), ('cat', '고양이')], max_length=100),
        ),
    ]
